### ISSUE TITLE
Google login seems to be broken

### ISSUE THREAD

**Issue by RobPFarley** [Supamiu/ffxiv-teamcraft#26] opened 2017-09-07 16:27 UTC
I created an account earlier using the Register with Google button, however when i try to Log In with Google nothing really happens, the Login/Registration buttons on the left change to one Disconnect button for about a second then change back to the Login/Register buttons

**Comment by Supamiu** [comment] 2017-09-07 16:55
I just tested the feature, it worked fine.

I think that you're not logging in with the right email, as we don't show any error messages in this case, the popup simply closes as the login is not successful.

Can you please give me your email used for the google account on discord? https://discord.gg/r6qxt6P

Giving an email here can be an issue if this page is parsed by bots, you could find your email where you don't want it to be 😉

**Comment by Supamiu** [comment] 2017-09-08 06:23
I'm closing the issue as invalid because I can't reproduce the bug and it seems like it's just a wrong account issue.

**Closed by Supamiu** 2017-09-08 06:23 UTC
Labels: invalid
