### ISSUE TITLE
feat: Remove silenced alarm groups from timers list

### ISSUE THREAD

**Issue by RobPFarley** [Supamiu/ffxiv-teamcraft#461] opened 2018-07-04 00:11 UTC
## What feature are you proposing
Currently we are able to silence an alarm group, which prevents the alert sounds from being played, however the nodes within that group still appear in the timers list on the right.

Could we make it so that if a group is silenced in the alarms section, the nodes from that group no longer appear in the timers list? Or add an option to the groups to hide the nodes as well as silence them. This makes the timers much more customisable, as I find myself often switching which items I'm gathering, but I can't filter out nodes I'm not interested in at the current time

**Comment by Supamiu** [comment] 2018-07-04 09:16
Hi, thanks for the feature request, this has already been asked and will be done soon, see #452 😄 

I'm closing this issue as duplicate of #452 , but be sure it'll be done.

**Closed by Supamiu** 2018-07-04 09:16 UTC
Labels: duplicate

**Comment by RobPFarley** [comment] 2018-07-04 09:17
Ah sorry about that, I'll make sure to search open issues in the future :)
