### ISSUE TITLE
bug: Cobalt Ingot shard requirements not being added to total

### ISSUE THREAD

**Issue by MillhioreF** [Supamiu/ffxiv-teamcraft#214] opened 2018-02-14 23:44 UTC
Example: https://ffxivteamcraft.com/list/nvCXdUrdO5HYnIuwLT9D

No catalysts show up under the Crystals section, and if I click to check requirements on Cobalt Ingot the console throws an error.
Browser is latest Chrome if that makes a difference.

**Comment by Supamiu** [comment] 2018-02-15 08:15
Hi, thank you for the report 👍 

I cloned your list so I can play with it, is regenerating it fixing the issue?

**Comment by Supamiu** [comment] 2018-02-15 12:26
Alright, the issue is on Garlandtools' side: https://www.garlandtools.org/db/doc/item/en/2/5059.json

While waiting for the issue to be fixed on data side, you can recreate the list with the BSM recipe in order to make sure you have shards listed. just take them as fire ones.

**Comment by MillhioreF** [comment] 2018-02-15 19:18
Thanks for the tip! BSM recipe works fine, GSM doesn't.

**Comment by Supamiu** [comment] 2018-02-15 19:33
It's fixed now, once this issue has been closed, it'll mean that it's in production (live server)

**Closed** 2018-02-15 22:00 UTC
Labels: bug, difficulty: very hard
