### ISSUE TITLE
bug: Wrong quantity

### ISSUE THREAD

**Issue by Chazalis** [Supamiu/ffxiv-teamcraft#317] opened 2018-04-16 03:25 UTC
### Browser
Windows NT 10.0; Win64; x64 Chrome/65.0.3325.181 

## Current behavior
If only one object is needed on an object crafted by 3, then it displays 0 as the quantity for the necessary resources instead of displaying 1.
Since the quantity needed is 0.33, it rounds to 0, whereas it will always have to round to the higher quantity as soon as there is a decimal.

**Comment by Supamiu** [comment] 2018-04-16 07:51
Hi, thank you for your report.

Can you please link a list as example or specify steps to reproduce so I can find out where this is coming from?

**Comment by Supamiu** [comment] 2018-04-16 08:48
I'm closing it because once 3.5.0 goes live, this will be fixed 👍

**Closed by Supamiu** 2018-04-16 08:48 UTC
Labels: bug, difficulty: easy, more details needed
